# Generated by Django 3.2.8 on 2022-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220201_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
