# Generated by Django 3.2.8 on 2022-02-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_user_is_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticrequest',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
